name: json_to_model
description: Gernerate model class from Json file. partly inspired by json_model.
version: 1.3.14
homepage: https://github.com/fadhilx/json_to_model

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.0

  args: ^1.5.2
  build_runner_core: ^5.1.0

  io: ^0.3.3
  logging: ^0.11.4

  expressions: ^0.1.5
  build_runner: ^1.9.0
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
